profile = high-quality
vo = gpu-next
gpu-api = vulkan # change to `opengl` if have issues
hwdec = auto-safe

keep-open = yes 
cursor-autohide = 1000 # 1s

screenshot-format = png
screenshot-dir = ~/Pictures/screenshots/mpv

sub-auto = fuzzy

deband = yes
deband-iterations = 4
deband-threshold = 48
deband-range = 16
deband-grain = 0
